// Firmware SNN controller wrapper.
//
// Responsibilities:
// - Apply exported scaler to analog context features
// - Reproduce the Python DeltaEncoder (pos/neg spike channels)
// - Call the fixed-point inference kernel and de-quantize to physical units
// - Maintain controller state (integral + encoder state) across timesteps
#include "snn.h"
#include "inference.h"
#include "profiler.h"
#ifndef SKIP_CONTROLLER_REGISTRATION
#include "comm.h"
#include "controller.h"
#endif
#include <math.h>
#include <stdio.h>
#include <string.h>

// Model/scaler globals are defined in inference.c, so we reference them via
// extern here.
extern const float SCALER_MIN[];
extern const float SCALER_RANGE[];
extern const float FEATURE_CLIP_MIN[];
extern const float FEATURE_CLIP_MAX[];

static int32_t input_buffer[SNN_MAX_INPUT_SIZE];
static float last_error_val = 0.0f;
static float integral_error = 0.0f;
static float prev_output = 0.0f;
static int snn_dbg_steps = 0;

// Output EMA alpha and actuator limits come from the auto-generated
// model_config.h. The #ifndef guards below are fallbacks for builds without an
// exported model.
#include "model_config.h"
#ifndef NC_SNN_OUTPUT_EMA_ALPHA
#define NC_SNN_OUTPUT_EMA_ALPHA 0.9f
#endif

#ifndef NC_SNN_ERR_DEADBAND_DEG
#define NC_SNN_ERR_DEADBAND_DEG 0.15f
#endif
#ifndef NC_SNN_OUTPUT_CENTER
#define NC_SNN_OUTPUT_CENTER 0.5f
#endif
#ifndef NC_SNN_ENCODER_RATE_MAX_INPUT
#define NC_SNN_ENCODER_RATE_MAX_INPUT 1.0f
#endif
#ifndef NC_SNN_ENCODER_RATE_ZERO_POINT
#define NC_SNN_ENCODER_RATE_ZERO_POINT 0.0f
#endif
#define SNN_FILTER_ALPHA NC_SNN_OUTPUT_EMA_ALPHA

// Per-feature encoder state for delta/rate encoding
#define NC_SNN_MAX_FEATURES 5
static float encoder_prev_value[NC_SNN_MAX_FEATURES];
static bool encoder_feat_init[NC_SNN_MAX_FEATURES];
static float encoder_delta_threshold_f = 0.0f;

// Store frequently-used model configuration constants.
// This keeps the wrapper independent from model_data.h.
static struct {
  int context_size;
  int spike_size;
  int input_frac_bits;
  int32_t encoder_delta_threshold;
  float output_scale;
} model_config_cache;

// Helper: Apply the exported scaler to a single raw feature value.
// The exporter provides SCALER_MIN and SCALER_RANGE (range = max - min),
// matching:
//   scaled = (x - min) / range
// producing an approximately [0, 1] normalized value under training conditions.
static float apply_scaler(float raw_value, int feature_idx) {
  if (feature_idx < 0 || feature_idx >= SCALER_DIM) {
    return 0.0f;
  }

  float min_val = SCALER_MIN[feature_idx];
  float range = SCALER_RANGE[feature_idx];

  if (range < 1e-6f) {
    return 0.0f; // Prevent division by zero
  }

  return (raw_value - min_val) / range;
}

static float apply_feature_clip(float raw_value, int feature_idx) {
  if (raw_value < FEATURE_CLIP_MIN[feature_idx])
    return FEATURE_CLIP_MIN[feature_idx];
  if (raw_value > FEATURE_CLIP_MAX[feature_idx])
    return FEATURE_CLIP_MAX[feature_idx];
  return raw_value;
}

static struct {
  float min_output;
  float max_output;
} snn_params = {.min_output = -1.0f, .max_output = 1.0f};

void snn_reset(void) {
  snn_inference_reset();

  model_config_cache.context_size = snn_get_context_size();
  model_config_cache.spike_size = snn_get_spike_size();
  model_config_cache.input_frac_bits = snn_get_input_frac_bits();
  model_config_cache.encoder_delta_threshold =
      snn_get_encoder_delta_threshold();
  model_config_cache.output_scale = snn_get_output_scale();

  /* Apply actuator limits exported by synthesis.  NC_SNN_U_MIN / NC_SNN_U_MAX
   * are defined in model_data.h (generated by neucode.exporters.snn).  If an
   * old header without these defines is used, the #ifndef guards below keep the
   * +/-1.0 defaults. */
#ifndef NC_SNN_U_MIN
#define NC_SNN_U_MIN -1.0f
#endif
#ifndef NC_SNN_U_MAX
#define NC_SNN_U_MAX 1.0f
#endif
  snn_set_output_limits(NC_SNN_U_MIN, NC_SNN_U_MAX);

  // Convert exported fixed-point delta threshold back to float (raw error)
  // domain. Exporter encodes: ENCODER_DELTA_THRESHOLD = round(delta_threshold *
  // (1 << INPUT_FRAC_BITS)) Python DeltaEncoder applies delta_threshold in the
  // unscaled error domain.
  encoder_delta_threshold_f = 0.0f;
  if (model_config_cache.input_frac_bits >= 0) {
    encoder_delta_threshold_f =
        (float)model_config_cache.encoder_delta_threshold /
        (float)(1 << model_config_cache.input_frac_bits);
  }

  last_error_val = 0.0f;
  memset(input_buffer, 0, sizeof(input_buffer));

  memset(encoder_prev_value, 0, sizeof(encoder_prev_value));
  memset(encoder_feat_init, 0, sizeof(encoder_feat_init));
  prev_output = 0.0f;

  snn_dbg_steps = 0;
}

// Per-feature delta spike generation (mirrors DeltaEncoder / HybridSpikeEncoder).
// Computes both polarities for the given feature in one call so prev_value
// is updated exactly once.
static void snn_compute_delta_spike(int feat, float value, int32_t *pos, int32_t *neg) {
  *pos = 0;
  *neg = 0;

  if (!encoder_feat_init[feat]) {
    encoder_prev_value[feat] = value;
    encoder_feat_init[feat] = true;
    return;
  }

  const float diff = value - encoder_prev_value[feat];
  if (diff > encoder_delta_threshold_f) {
    *pos = 1;
    encoder_prev_value[feat] += encoder_delta_threshold_f;
  } else if (diff < -encoder_delta_threshold_f) {
    *neg = 1;
    encoder_prev_value[feat] -= encoder_delta_threshold_f;
  }
}

// Per-feature rate spike generation (mirrors HybridSpikeEncoder rate branch).
// Rate is proportional to |value - zero_point| / max_input, clamped to [0,1].
static void snn_compute_rate_spike(float value, int32_t *pos, int32_t *neg) {
  *pos = 0;
  *neg = 0;
  float centered = value - NC_SNN_ENCODER_RATE_ZERO_POINT;
  float rate = fabsf(centered) / NC_SNN_ENCODER_RATE_MAX_INPUT;
  if (rate > 1.0f) rate = 1.0f;

  int32_t rate_q =
      (int32_t)(rate * (1 << model_config_cache.input_frac_bits));
  if (centered > 0.0f) {
    *pos = rate_q;
  } else if (centered < 0.0f) {
    *neg = rate_q;
  }
}

static float snn_update(float sp, float y, float dt) {
  float error = sp - y;
  float derivative_error = 0.0f;

  if (dt > 1e-12f) {
    derivative_error = (error - last_error_val) / dt;
  }

  // Compute raw (clipped) and scaled features
  float raw_features[] = {sp, y, error, integral_error, derivative_error};
  float clipped[NC_SNN_MAX_FEATURES];
  float scaled[NC_SNN_MAX_FEATURES];
  for (int i = 0; i < SCALER_DIM && i < NC_SNN_MAX_FEATURES; i++) {
    clipped[i] = apply_feature_clip(raw_features[i], i);
    scaled[i] = apply_scaler(clipped[i], i);
  }

  // Pre-compute delta and rate spikes per feature (on demand)
  bool delta_done[NC_SNN_MAX_FEATURES] = {false};
  int32_t delta_result[NC_SNN_MAX_FEATURES][2];
  bool rate_done[NC_SNN_MAX_FEATURES] = {false};
  int32_t rate_result[NC_SNN_MAX_FEATURES][2];
  memset(delta_result, 0, sizeof(delta_result));
  memset(rate_result, 0, sizeof(rate_result));

  // Fill input buffer from exported channel descriptors
  for (int ch = 0; ch < INPUT_CHANNEL_COUNT && ch < SNN_MAX_INPUT_SIZE; ch++) {
    uint8_t type = INPUT_CHANNEL_TYPE[ch];
    uint8_t feat = INPUT_CHANNEL_FEATURE[ch];
    uint8_t pol = INPUT_CHANNEL_POLARITY[ch];

    if (type == NC_INPUT_CONTEXT) {
      input_buffer[ch] =
          (int32_t)(scaled[feat] * (1 << model_config_cache.input_frac_bits));
    } else if (type == NC_INPUT_DELTA) {
      // Delta encoding uses raw (clipped) values, not scaled -- matches
      // the original firmware behavior that DAgger models were trained against.
      if (!delta_done[feat]) {
        snn_compute_delta_spike(feat, clipped[feat],
                                &delta_result[feat][0], &delta_result[feat][1]);
        delta_done[feat] = true;
      }
      input_buffer[ch] = delta_result[feat][pol];
    } else if (type == NC_INPUT_RATE) {
      if (!rate_done[feat]) {
        snn_compute_rate_spike(scaled[feat],
                               &rate_result[feat][0], &rate_result[feat][1]);
        rate_done[feat] = true;
      }
      input_buffer[ch] = rate_result[feat][pol];
    }
  }

  // Run SNN inference to get the raw integer sum
  int32_t raw_sum = snn_inference(input_buffer);

  // Convert raw int32 sum into physical output units.
  // Matches verify_snn: OUTPUT_SCALE / (1 << OUTPUT_WEIGHT_SHIFT).
  float out = (float)raw_sum * snn_get_output_scale_factor();

  // Per-experiment inference diagnostics: log spike count and pre-EMA output
  // for the first 3 steps. Useful for verifying C/Python numerical match on
  // hardware.
  if (snn_dbg_steps < 3) {
    char dbg_buf[80];
    snprintf(dbg_buf, sizeof(dbg_buf),
             "info: SNN dbg step=%d raw=%ld sf=%.5f pre=%.4f", snn_dbg_steps,
             (long)raw_sum, snn_get_output_scale_factor(), out);
    nc_comm_send_log(dbg_buf);
    snn_dbg_steps++;
  }

  // Apply output centering shift to align the network output range with the
  // actuator command range, matching the training-time output normalisation.
  out -= NC_SNN_OUTPUT_CENTER * model_config_cache.output_scale;
  return out;
}

void snn_set_output_limits(float u_min, float u_max) {
  snn_params.min_output = u_min;
  snn_params.max_output = u_max;
}

float snn_step(float sp, float y, float dt) {
  const float error = sp - y;

  // Match Python startup deadband behavior: when near-zero setpoint and small
  // error, reset neuron and encoder state to avoid background firing.
  if (fabsf(sp) < 0.001f && fabsf(error) < 0.05f) {
    snn_inference_reset();
    memset(encoder_feat_init, 0, sizeof(encoder_feat_init));
    prev_output = 0.0f;
    return 0.0f;
  }

  // General error deadband: suppress output jitter near setpoint
  if (fabsf(error) < NC_SNN_ERR_DEADBAND_DEG) {
    prev_output = 0.0f;
    return 0.0f;
  }

  float output = snn_update(sp, y, dt);

  // EMA filter on output: suppresses spike-induced noise in the SNN output
  // signal.
  output = SNN_FILTER_ALPHA * output + (1.0f - SNN_FILTER_ALPHA) * prev_output;
  prev_output = output;

  // Update derivative state for next step
  last_error_val = error;

  integral_error += error * dt;

  // Clip integral to exported per-feature bounds (index 3).
  integral_error = apply_feature_clip(integral_error, 3);

  // Clamp output to actuator limits
  if (output > snn_params.max_output) {
    output = snn_params.max_output;
  } else if (output < snn_params.min_output) {
    output = snn_params.min_output;
  }

  return output;
}

#ifndef SKIP_CONTROLLER_REGISTRATION
static void snn_adapter_init(void) { snn_reset(); }

static void snn_adapter_reset(void) { snn_reset(); }

// SNN config is baked into the exported model - nothing to set at runtime.
static void snn_adapter_set_params(const void *params, size_t params_size) {
  (void)params;
  (void)params_size;
}

static double snn_adapter_step(double sp, double y, double dt) {
  return (double)snn_step((float)sp, (float)y, (float)dt);
}

void snn_benchmark(uint32_t n) {
  snn_reset();
  snn_dbg_steps = 3;

  uint32_t cycles_sum = 0;
  uint32_t cycles_min = 0xFFFFFFFFu;
  uint32_t cycles_max = 0;

  for (uint32_t i = 0; i < n; i++) {
    uint32_t t_start = profiler_get_cycles();
    snn_step(22.5f, 0.0f, 0.001f);
    uint32_t t_end = profiler_get_cycles();
    uint32_t cycles = t_end - t_start;
    cycles_sum += cycles;
    if (cycles < cycles_min)
      cycles_min = cycles;
    if (cycles > cycles_max)
      cycles_max = cycles;
  }

  uint32_t mean_cycles = cycles_sum / n;
  uint32_t mean_us = mean_cycles / 170;
  uint32_t mean_us_frac = (mean_cycles % 170) * 10 / 170;
  uint32_t min_us = cycles_min / 170;
  uint32_t max_us = cycles_max / 170;

  char buf[128];
  snprintf(buf, sizeof(buf),
           "bench snn: mean=%lu.%luus min=%luus max=%luus (n=%lu)",
           (unsigned long)mean_us, (unsigned long)mean_us_frac,
           (unsigned long)min_us, (unsigned long)max_us, (unsigned long)n);
  nc_comm_send_log(buf);
}

void nc_snn_controller_register(void) {
  nc_controller_register_mode(NC_CONTROLLER_MODE_SNN, snn_adapter_init,
                              snn_adapter_reset, snn_adapter_set_params,
                              snn_adapter_step);
}
#else
void nc_snn_controller_register(void) { /* no-op in SIL builds */ }
#endif
