"""
ANN model exporter for the NeuCoDe toolkit.

Converts a trained ANN (MLP) PyTorch model into a fixed-point C header file
using symmetric int8 weight quantisation and int32 bias accumulation.
"""
from __future__ import annotations
import json
import numpy as np

from pathlib import Path
from typing import Optional

from neucode.exporters.base import BaseExporter
from neucode._torch_optional import torch

class ANNExporter(BaseExporter):
    """
    Exporter for standard ANN (MLP) controllers.

    Quantises weights to int8 and biases to int32 using Q-format arithmetic,
    and writes a self-contained C header file that includes scaler parameters
    for firmware-side StandardScaler normalisation.
    """
    def __init__(self, total_bits: int = 8):
        """
        Initialize the ANNExporter with the specified total bits for fixed-point representation.
        
        :param total_bits: Total number of bits for fixed-point representation (default is 8).
        """
        self.total_bits = total_bits
    
    def export(self, model_path: str = None, stats_path: str = None,
               scaler_path: str = None, output_path: str = None,
               deployment_target: Optional[str] = None, actuator_limits: Optional[dict] = None,
               experiment=None, tag: str = None, deployment_type: str = None):
        """
        Export the ANN model to a C header file with fixed-point representation.
        Pipeline: Load Artifacts -> Normalize Input -> Quantize -> Write Header.

        Some more info about the quantization approach:
        - Input scaler parameters (mean, scale) are stored in header for firmware to apply.
        - This separates concerns: firmware normalizes raw sensor inputs, then quantizes to int8.
        - Weights are quantized to symmetric int8 and biases to int32 (to avoid overflow during accumulation).
        - Performant requantization requires right shift with a power-of-two scaling factor.
        - INPUT_FRAC_BITS now applies to normalized (scaled) inputs, allowing better quantization precision.

        The whole quantization/export approach is inspired by:
        - Jacob et al., "Quantization and Training of Neural Networks for Efficient Integer-Arithmetic-Only Inference", https://arxiv.org/pdf/1712.05877
         (Strict symmetric Q-format quantization and power-of-two bitshifts for requantization).
        - Lai et al., "CMSIS-NN: Efficient Neural Network Kernels for Arm Cortex-M CPUs", https://arxiv.org/pdf/1801.06601
          (int8 weights/activations, int32 accumulators, and the integer-only inference pipeline).

        :param model_path: Path to the trained PyTorch model.
        :param stats_path: Path to the calibration statistics JSON file.
        :param scaler_path: Path to the scaler parameters (mean and scale).
        :param output_path: Path to the output C header file.
        :param deployment_target: Optional deployment target specification.
        :param experiment: Optional Experiment instance for path resolution.
        :param tag: Training tag within the experiment (required when experiment is passed).
        :param deployment_type: Controller type ('ann', 'snn') for firmware deployment path.
        """
        # Resolve paths from experiment
        if experiment is not None:
            if tag is None:
                raise ValueError("tag is required when passing experiment")
            model_path = model_path or experiment.get_model_path(tag)
            stats_path = stats_path or experiment.get_stats_path(tag)
            scaler_path = scaler_path or experiment.get_scaler_path(tag)
            output_path = output_path or experiment.get_model_data_header_path(tag)
            if deployment_type:
                deployment_target = deployment_target or experiment.get_model_data_deployment_target_path(deployment_type)
            if actuator_limits is None:
                actuator_limits = experiment.actuator_limits or None
        # Load Model Weights
        state_dict = torch.load(model_path, map_location='cpu')
        state_dict = state_dict._orig_mod if hasattr(state_dict, '_orig_mod') else state_dict

        # Load Calibration Stats
        with open(stats_path, 'r') as f:
            stats = json.load(f)

        # Load Scaler
        scaler = np.load(scaler_path)
        scaler_mu = scaler['mean']
        scaler_sigma = scaler['scale']
        scaler_sigma[scaler_sigma == 0] = 1.0 #prevent division by zero

        # Store the scaler parameters in the header for firmware to apply
        c_header_content = [
            "// AUTO-GENERATED BY neucode.exporters.ann.ANNExporter",
            "// Scaler is applied by firmware BEFORE quantization to preserve input resolution",
            "#include <stdint.h>",
            "#include <stdbool.h>",
            ""
        ]
        
        # Add scaler parameters to header
        c_header_content.append("// Input Scaler Parameters (StandardScaler: (x - mean) / scale)")
        c_header_content.append(f"#define SCALER_DIM {len(scaler_mu)}")
        scaler_mean_str = ", ".join([f"{x:.8e}" for x in scaler_mu])
        c_header_content.append(f"static const float SCALER_MEAN[] = {{ {scaler_mean_str} }};")
        scaler_scale_str = ", ".join([f"{x:.8e}" for x in scaler_sigma])
        c_header_content.append(f"static const float SCALER_SCALE[] = {{ {scaler_scale_str} }};")
        # Emit derivative clip bound so firmware applies the same clamp as training
        deriv_clip = float(scaler['deriv_clip'][0]) if 'deriv_clip' in scaler.files else float('inf')
        c_header_content.append(f"// Derivative-error clamp applied before scaling (matches training p99 clip)")
        c_header_content.append(f"#define DERIV_CLIP_VALUE {deriv_clip:.8e}f")
        c_header_content.append("")

        # Emit actuator limits so firmware ann.c reads them via its #ifndef guards.
        # If actuator_limits is not provided, the firmware falls back to its hardcoded +/-1.0.
        if actuator_limits is not None:
            u_min = float(actuator_limits.get('u_min', -1.0))
            u_max = float(actuator_limits.get('u_max',  1.0))
            c_header_content.append("// Actuator output limits (read by firmware ann.c via #ifndef NC_ANN_U_MAX)")
            c_header_content.append(f"#define NC_ANN_U_MIN {u_min:.8e}f")
            c_header_content.append(f"#define NC_ANN_U_MAX {u_max:.8e}f")
            c_header_content.append("")

        layer_configs = []
        max_layer_dim = 0
        is_first_layer = True
        prev_n_out = 0
        prev_s_out = 1.0

        sorted_layers = sorted(stats.keys())

        for layer_name in sorted_layers:
            layer_stats = stats[layer_name]
            weight_key = f"{layer_name}.weight"
            bias_key = f"{layer_name}.bias"

            if weight_key not in state_dict:
                print(f"  No weights found for layer {layer_name}, skipping.")
                continue

            if layer_stats is None:
                print(f"  No calibration data for layer {layer_name}, skipping.")
                continue

            w_tensor = state_dict[weight_key].numpy()
            if bias_key in state_dict:
                b_tensor = state_dict[bias_key].numpy()
            else:
                b_tensor = np.zeros(w_tensor.shape[0])

            # Use weights and biases as-is (no scaler fusion)
            # Scaler will be applied by firmware before quantization
            w_final = w_tensor
            b_final = b_tensor
            
            # For first layer, set INPUT_FRAC_BITS based on normalized input range
            if is_first_layer:
                print("  Setting INPUT_FRAC_BITS for normalized input range.")
                in_max = layer_stats['in_maxabs']
                _, n_in, s_in = self._get_q_format(in_max)
                c_header_content.append(f"#define INPUT_FRAC_BITS {n_in}")
                is_first_layer = False
            else:
                n_in = prev_n_out
                s_in = prev_s_out

            # Quantization (using power-of-two scaling factors from Q-format)
            # Weights
            w_max = np.max(np.abs(w_final))
            _, n_w, s_w = self._get_q_format(w_max)
            # Outputs
            out_max = max(abs(layer_stats['out_min']), abs(layer_stats['out_max']))
            _, n_out, s_out = self._get_q_format(out_max)
            # Store the output Q-format for the next layer's input
            prev_n_out = n_out
            prev_s_out = s_out

            # Apply weights quantization
            # TODO: add np.clip(..., -128, 127) before astype to match SNN exporter convention;
            # currently relies on _get_q_format deriving m conservatively enough that no weight exceeds +/-127
            w_int8 = np.round(w_final * s_w).astype(np.int8)
            # Apply bias quantization (bias uses output scale)
            s_bias = s_in * s_w
            b_int32 = np.round(b_final * s_bias).astype(np.int32)
            # Shift calculation
            # How much to shift right after accumulation to get back to next layer's input Q-format
            # This is called Requantization -> Multiplying input * weights will result in a bigger number of integer bits
            # that need to be shifted to fit into next layer's format.
            shift = (n_in + n_w) - n_out
            # Shape info
            shape = w_final.shape
            out_dim = shape[0]
            in_dim = np.prod(shape[1:]) #just in case of conv layers later

            prefix = layer_name.upper()

            c_header_content.append(f"// {layer_name}")
            w_str = ", ".join(map(str, w_int8.flatten()))
            c_header_content.append(f"static const int8_t {prefix}_WEIGHTS[] = {{{w_str}}};")

            b_str = ", ".join(map(str, b_int32.flatten()))
            c_header_content.append(f"static const int32_t {prefix}_BIAS[] = {{ {b_str} }};")
            
            # Last layer output fractional bits definition
            if layer_name == sorted_layers[-1]:
                c_header_content.append(f"#define OUTPUT_FRAC_BITS {n_out}")
            c_header_content.append("")

            # Check if the current layer should have a relu activation applied
            # We don't really check the model, we just assume all layers except the last have relu
            has_relu = "true" if layer_name != sorted_layers[-1] else "false"

            layer_configs.append({
                'layer_name': prefix,
                'in_dim': in_dim,
                'out_dim': out_dim,
                'shift': shift,
                'has_relu': has_relu
            })

            max_layer_dim = max(max_layer_dim, in_dim, out_dim)

        c_header_content.append("// Layer Configurations")
        c_header_content.append(f"#define NUM_LAYERS {len(layer_configs)}")
        c_header_content.append(f"#define MAX_LAYER_DIM {max_layer_dim}")

        c_header_content.append("// Pointers to layer data")
        c_header_content.append(f"static const int8_t* const WEIGHT_POINTERS[] = {{ " + ", ".join([f"{cfg['layer_name']}_WEIGHTS" for cfg in layer_configs]) + " };")
        c_header_content.append(f"static const int32_t* const BIAS_POINTERS[] = {{ " + ", ".join([f"{cfg['layer_name']}_BIAS" for cfg in layer_configs]) + " };")

        c_header_content.append("// Layer parameters")
        c_header_content.append(f"static const int LAYER_SHIFTS[] = {{ " + ", ".join([str(cfg['shift']) for cfg in layer_configs]) + " };")
        c_header_content.append(f"static const int LAYER_IN_DIMS[] = {{ " + ", ".join([str(cfg['in_dim']) for cfg in layer_configs]) + " };")
        c_header_content.append(f"static const int LAYER_OUT_DIMS[] = {{ " + ", ".join([str(cfg['out_dim']) for cfg in layer_configs]) + " };")
        c_header_content.append(f"static const bool LAYER_HAS_RELU[] = {{ " + ", ".join([cfg['has_relu'] for cfg in layer_configs]) + " };")

        output_path = Path(output_path)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(c_header_content), encoding='utf-8')

        if deployment_target:
            deployment_path = Path(deployment_target)
            deployment_path.parent.mkdir(parents=True, exist_ok=True)
            deployment_path.write_text("\n".join(c_header_content), encoding='utf-8')

        print(f"* Exported ANN model to {output_path}")
