"""
Dataset generation utilities for the NeuCoDe pipeline.

Provides TuningDatasetGenerator (plant -> optimal PID gains via differential evolution)
and ReplacementDatasetGenerator (plant -> closed-loop trajectory for imitation learning).
"""
from __future__ import annotations
from scipy.optimize import differential_evolution
from collections.abc import Callable
import numpy as np
import pandas as pd

from .rewards import BaseReward
from .scenarios import BenchmarkScenario
from .harness import SimulationHarness
from .plants import Plant
from .controllers import PIDController, Controller
from .tuners import SupervisedTuner
from .generators import BasePlantGenerator
from .ui import get_progress_bar

class _BaseDatasetGenerator:
    """
    (Internal) Base class for dataset generators.
    """
    def __init__(self,
                 plant_generator: BasePlantGenerator,
                 benchmark: BenchmarkScenario,
                 actuator_limits: dict,
                 dt: float):
        """
        Initialize the base dataset generator.

        :param plant_generator: Generator that produces (plant, observation) pairs.
        :param benchmark: Benchmark scenario used to evaluate each sampled plant.
        :param actuator_limits: Dict with 'u_min' and 'u_max' keys for output clamping.
        :param dt: Simulation time step in seconds.
        """
        self.benchmark = benchmark
        self.actuator_limits = actuator_limits
        self.plant_generator = plant_generator
        self.dt = dt
        self.harness = SimulationHarness(
            plant=None,
            controller=None,
            setpoint=None,
            actuator_limits=actuator_limits
        )

class TuningDatasetGenerator(_BaseDatasetGenerator):
    """
    Builder class that generates PID tuning datasets.
    A global optimization algorithm is used to find optimal PID gains
    for plants generated by a given plant generator.
    """
    def __init__(self,
                 plant_generator: BasePlantGenerator,
                 reward_strategy: BaseReward,
                 benchmark: BenchmarkScenario,
                 actuator_limits: dict,
                 gains_search_space: list[tuple[float, float]],
                 dt: float):
        """
        Initialize the tuning dataset generator.

        :param plant_generator: Generator that produces (plant, observation) pairs.
        :param reward_strategy: Reward function used to score each candidate gain triple.
        :param benchmark: Benchmark scenario run for each DE population evaluation.
        :param actuator_limits: Dict with 'u_min' and 'u_max' keys for output clamping.
        :param gains_search_space: List of (min, max) bounds for (kp, ki, kd_industrial).
        :param dt: Simulation time step in seconds.
        """
        super().__init__(plant_generator, benchmark, actuator_limits, dt)
        self.reward_strategy = reward_strategy
        self.gains_search_space = gains_search_space

    def _objective_function(self, gains: np.ndarray, plant: Plant) -> float:
        """
        Evaluate the cost of a candidate gain triple on a specific plant.

        Called by differential_evolution for each population member. Configures
        the shared harness with the given gains, runs the benchmark, and returns
        the scalar cost from the reward strategy.

        :param gains: Array of [kp, ki, kd_industrial] candidate gains.
        :param plant: Plant instance to evaluate the gains on.
        :return: Scalar cost value (lower is better).
        """
        kp, ki, kd_industrial = gains

        # Create and set the PID controller with the given gains
        pid_controller = PIDController(kp=float(kp), ki=float(ki), kd=float(kd_industrial))
        self.harness.set_plant(plant)
        self.harness.set_controller(pid_controller)

        # Run the benchmark scenario
        result = self.benchmark.run(self.harness, get_time_series=False)

        # Calculate and return the reward (negative cost)
        cost = self.reward_strategy.calculate_cost(result)
        return cost
    
    def generate(self, num_samples: int, output_file: str):
        """
        Generate a tuning dataset by running differential evolution for each sampled plant.

        For each sample, DE searches the configured gains space to minimize the reward
        cost. On convergence, the winning gains are re-evaluated with full metrics and
        appended as a row to the output CSV. Failed optimizations are skipped.

        :param num_samples: Number of plants to sample and optimize.
        :param output_file: Path to write the resulting CSV dataset.
        """
        print(f"* Generating dataset with {num_samples} samples...")
        data = []

        obs_dim = self.plant_generator.get_observation_space().shape[0]

        with get_progress_bar("Generating samples...", total=num_samples) as progress:
            for _ in range(num_samples):
                plant, obs = self.plant_generator.generate()
                # Differential-Evolution settings for the PID gain search.
                result = differential_evolution(
                    self._objective_function,
                    bounds=self.gains_search_space,
                    args=(plant,),
                    strategy='best1bin',
                    maxiter=1000,
                    disp=False,
                    workers=-1,
                    updating='deferred'
                )
                if result.success:
                    kp_opt, ki_opt, kd_opt_industrial = result.x

                    # we re-run the simulation to get full metrics
                    pid_controller = PIDController(kp=float(kp_opt), ki=float(ki_opt), kd=float(kd_opt_industrial))
                    self.harness.set_plant(plant)
                    self.harness.set_controller(pid_controller)

                    result_full = self.benchmark.run(self.harness, get_time_series=False)

                    row = {}
                    for j in range(obs_dim):
                        row[f"obs_{j}"] = obs[j]

                    row['kp_optimal'] = kp_opt
                    row['ki_optimal'] = ki_opt
                    row['kd_optimal_industrial'] = kd_opt_industrial
                    row['final_cost'] = result.fun
                    row['itae'] = result_full.itae
                    row['isu'] = result_full.isu

                    data.append(row)
                else:
                    print("Warning: Optimization failed for a sample. Skipping.")
                progress.update()

        # Save the dataset to a CSV file
        df = pd.DataFrame(data)
        df.to_csv(output_file, index=False)
        print(f"* Dataset generation complete. Saved to '{output_file}'.")

class ReplacementDatasetGenerator(_BaseDatasetGenerator):
    """
    Builder class that generates PID replacement datasets.
    A supervised learning dataset is created by simulating plants
    generated by a given plant generator with "optimal" PID controllers.

    Note: You need to have trained a SupervisedTuner beforehand to provide
    the optimal PID gains for each plant.

    Supports dynamic Benchmark generation for Domain Randomization.
    """
    def __init__(self,
                 plant_generator: BasePlantGenerator,
                 benchmark: BenchmarkScenario | Callable[[], BenchmarkScenario],
                 dt: float,
                 tuner: SupervisedTuner = None,
                 actuator_limits: dict = None,
                 controller: Controller = None):
        """
        Initialize the replacement dataset generator.

        :param plant_generator: Generator that produces (plant, observation) pairs.
        :param benchmark: A fixed BenchmarkScenario or a zero-argument callable that
            returns a fresh scenario per episode (for domain randomization).
        :param dt: Simulation time step in seconds.
        :param tuner: Trained SupervisedTuner used to obtain PID gains for each plant.
        :param actuator_limits: Optional dict with 'u_min' and 'u_max' keys.
        :param controller: Fixed controller to reuse for every episode. Mutually
            exclusive with tuner -- provide exactly one.
        """
        super().__init__(plant_generator, None, actuator_limits, dt)
        if tuner is not None and controller is not None:
            raise ValueError("Provide either tuner or controller, not both.")
        if tuner is not None:
            if not isinstance(tuner, SupervisedTuner):
                raise TypeError("tuner must be an instance of SupervisedTuner.")
            self._get_controller = tuner.tune
        elif controller is not None:
            self._get_controller = lambda plant: controller
        else:
            raise ValueError("Either tuner or controller must be provided.")
        self.benchmark_provider = benchmark if callable(benchmark) else lambda: benchmark

    def generate(self, num_samples: int, output_file: str):
        """
        Generate a replacement dataset of closed-loop trajectories for imitation learning.

        For each sampled plant the tuner predicts optimal PID gains, the benchmark runs
        to produce a full time-series trajectory, and derived features (error,
        integral_error, derivative_error) are appended. Each trajectory is assigned a
        monotonically incrementing episode_id. Plant observation columns are stamped
        identically across every row of an episode.

        :param num_samples: Number of plants (episodes) to simulate.
        :param output_file: Path to write the resulting CSV dataset.
        """
        print(f"* Generating PID replacement dataset with {num_samples} samples...")
        all_time_series_dfs = []
        episode_count = 0

        with get_progress_bar("Generating samples...", total=num_samples) as progress:
            for i in range(num_samples):
                plant, obs = self.plant_generator.generate()

                optimal_controller = self._get_controller(plant)

                self.harness.set_plant(plant)
                self.harness.set_controller(optimal_controller)

                # Allow dynamic benchmarks
                current_benchmark = self.benchmark_provider()

                # We need the time series this time
                result = current_benchmark.run(self.harness, get_time_series=True)

                if result.success and result.time_series is not None:
                    df = pd.DataFrame(result.time_series)

                    df['episode_id'] = episode_count
                    episode_count += 1

                    # Pre-compute Error
                    df['error'] = df['setpoint'] - df['measurement']

                    if self.actuator_limits is not None:
                        max_u = float(self.actuator_limits.get('u_max', float('inf')))
                        min_u = float(self.actuator_limits.get('u_min', float('-inf')))
                    else:
                        max_u = float('inf')
                        min_u = float('-inf')

                    # Integral feature: plain cumsum - no anti-windup on the feature, matches inference exactly.
                    integral_array = np.cumsum(df['error'].values) * self.dt

                    df['integral_error'] = integral_array

                    # Pre-compute Integral and Derivative of Error
                    df['derivative_error'] = df['error'].diff() / self.dt
                    df['derivative_error'] = df['derivative_error'].fillna(0.0)

                    # Add plant observation columns to every row of the time series
                    for j, obs_val in enumerate(obs):
                        df[f"obs_{j}"] = obs_val

                    all_time_series_dfs.append(df)
                progress.update()

        final_df = pd.concat(all_time_series_dfs, ignore_index=True)
        final_df.to_csv(output_file, index=False)
        print(f"* Replacement dataset generation complete. Saved to '{output_file}'.")