from __future__ import annotations
from abc import ABC, abstractmethod
from gymnasium import spaces
import numpy as np

from .plants import Plant, FOPDTPlant, FOIPDTPlant

class BasePlantGenerator(ABC):
    """
    Base class for plant generators.
    """
    @abstractmethod
    def get_observation_space(self) -> spaces.Box:
        """
        Return the observation space for the plant.
        """
        pass

    @abstractmethod
    def generate(self) -> tuple[Plant, np.ndarray]:
        """
        Return the set plant instance and its observation array.
        """
        pass

class FOPDTPlantGenerator(BasePlantGenerator):
    """
    First-Order Plus Dead Time (FOPDT) Plant Generator.
    Always returns the same, specified plant and observation.
    """
    def __init__(self, plant: FOPDTPlant):
        if not isinstance(plant, FOPDTPlant):
            raise TypeError("plant must be an instance of FOPDTPlant.")
        self._plant = plant

        self._obs = np.array([
            plant.params['K'], plant.params['tau'], plant.params['theta']
        ], dtype=np.float32)

        # We keep the observation space fixed for this generator
        # as the plant parameters are fixed.
        self._observation_space = spaces.Box(
            low=self._obs,
            high=self._obs,
            dtype=np.float32
        )

    def get_observation_space(self) -> spaces.Box:
        """
        Return the observation space for the FOPDT plant.
        """
        return self._observation_space
    
    def generate(self) -> tuple[FOPDTPlant, np.ndarray]:
        """
        Return the FOPDT plant instance and its observation array.
        """
        return self._plant, self._obs
    
class StratifiedGeneratorWrapper(BasePlantGenerator):
    """
    A plant-agnostic wrapper that applies uniform domain randomization 
    to any plant generated by the underlying base_generator.
    """
    def __init__(self, base_generator: BasePlantGenerator, variance_pct: float = 0.15, seed: int = None):
        """
        :param base_generator: An instance of a BasePlantGenerator (e.g., FOPDTPlantGenerator).
        :param variance_pct: The +/- variance to apply to the plant parameters (e.g., 0.15).
        :param seed: Optional random seed for reproducible parameter perturbations.
        """
        super().__init__()
        self.base_generator = base_generator
        self.variance_pct = variance_pct
        self._rng = np.random.default_rng(seed)

        # Dynamically expand the observation space boundaries by the variance percentage
        base_space = self.base_generator.get_observation_space()
        if base_space is not None:
            # Absolute value because we need to expand in both directions
            delta_low = np.abs(base_space.low) * self.variance_pct
            delta_high = np.abs(base_space.high) * self.variance_pct
            
            self._observation_space = spaces.Box(
                low=base_space.low - delta_low,
                high=base_space.high + delta_high,
                dtype=np.float32
            )
        else:
            self._observation_space = None

    def get_observation_space(self):
        """
        Return the dynamically expanded observation space.
        """
        return self._observation_space

    def generate(self) -> tuple[object, np.ndarray]:
        """
        Generates a nominal plant, mutates its parameters, and returns the randomized plant.
        """
        # Get the nominal plant from the base generator
        nominal_plant, _ = self.base_generator.generate()

        # Extract its parameters (assuming the base plant has a .params dict)
        params = nominal_plant.params

        # Apply uniform variance to all numeric parameters
        mutated_params = {}
        for key, val in params.items():
            if isinstance(val, (int, float, np.number)):
                multiplier = self._rng.uniform(1.0 - self.variance_pct, 1.0 + self.variance_pct)
                mutated_params[key] = float(val * multiplier)
            else:
                mutated_params[key] = val # Pass through any non-numeric parameters

        # Instantiate a new plant of the EXACT SAME CLASS
        # This makes the wrapper 100% plant-agnostic (FOPDT, SOPDT, etc.)
        mutated_plant = type(nominal_plant)(**mutated_params)

        # Extract the new observation vector from the mutated plant
        # Assuming your base plants have a get_observation_vector() method
        mutated_obs = mutated_plant.get_observation_vector()

        return mutated_plant, mutated_obs
    
class RandomFOPDTPlantGenerator(BasePlantGenerator):
    """
    Random FOPDT Plant Generator.
    Generates FOPDT plants with random parameters within a observation space.
    Stratified Sampling to be able to "evenly" create "easy" and "hard" plants by controlling
    the ratio of tau/theta.
    -> see: Simple analytic rules for model reduction and PID controller tuning (Skogestad, 2003)
    """
    def __init__(self, K_range: tuple[float, float], tau_range: tuple[float, float], ratio_range: tuple[float, float], seed: int = None):
        self.K_range = K_range
        self.tau_range = tau_range
        self.ratio_range = ratio_range
        self._rng = np.random.default_rng(seed)

        self._observation_space = spaces.Box(
            low=np.array([K_range[0], tau_range[0], tau_range[0] * ratio_range[0]], dtype=np.float32),
            high=np.array([K_range[1], tau_range[1], tau_range[1] * ratio_range[1]], dtype=np.float32),
            dtype=np.float32
        )

    def get_observation_space(self) -> spaces.Box:
        """
        Return the observation space for the ranged FOPDT plant.
        """
        return self._observation_space

    def generate(self) -> tuple[FOPDTPlant, np.ndarray]:
        """
        Generate a random FOPDT plant and return it along with its observation array.
        """
        K = self._rng.uniform(self.K_range[0], self.K_range[1])
        tau = self._rng.uniform(self.tau_range[0], self.tau_range[1])
        ratio = self._rng.uniform(self.ratio_range[0], self.ratio_range[1])
        
        theta = tau * ratio

        plant = FOPDTPlant(K=float(K), tau=float(tau), theta=float(theta))
        obs = plant.get_observation_vector()

        return plant, obs


class FOIPDTPlantGenerator(BasePlantGenerator):
    """
    Fixed FOIPDT Plant Generator.
    Always returns the same specified FOIPDT plant and its observation vector.
    """
    def __init__(self, plant: FOIPDTPlant):
        if not isinstance(plant, FOIPDTPlant):
            raise TypeError("plant must be an instance of FOIPDTPlant.")
        self._plant = plant

        self._obs = np.array(
            [plant.params['Kv'], plant.params['tau'], plant.params['theta']],
            dtype=np.float32
        )
        self._observation_space = spaces.Box(
            low=self._obs, high=self._obs, dtype=np.float32
        )

    def get_observation_space(self) -> spaces.Box:
        return self._observation_space

    def generate(self) -> tuple[FOIPDTPlant, np.ndarray]:
        return self._plant, self._obs


class RandomFOIPDTPlantGenerator(BasePlantGenerator):
    """
    Random FOIPDT Plant Generator.
    Generates FOIPDT plants with random velocity gain, lag, and dead time within
    specified ranges using stratified sampling on the tau/theta ratio.
    """
    def __init__(self, Kv_range: tuple[float, float], tau_range: tuple[float, float],
                 ratio_range: tuple[float, float], seed: int = None):
        """
        :param Kv_range: (min, max) range for the velocity gain Kv.
        :param tau_range: (min, max) range for the velocity lag tau.
        :param ratio_range: (min, max) range for the dead-time ratio theta/tau.
        :param seed: Optional random seed for reproducibility.
        """
        self.Kv_range = Kv_range
        self.tau_range = tau_range
        self.ratio_range = ratio_range
        self._rng = np.random.default_rng(seed)

        self._observation_space = spaces.Box(
            low=np.array([Kv_range[0], tau_range[0], tau_range[0] * ratio_range[0]], dtype=np.float32),
            high=np.array([Kv_range[1], tau_range[1], tau_range[1] * ratio_range[1]], dtype=np.float32),
            dtype=np.float32
        )

    def get_observation_space(self) -> spaces.Box:
        """
        Return the observation space for the ranged FOIPDT plant.
        """
        return self._observation_space

    def generate(self) -> tuple[FOIPDTPlant, np.ndarray]:
        """
        Generate a random FOIPDT plant and return it with its observation array.
        """
        Kv    = self._rng.uniform(self.Kv_range[0], self.Kv_range[1])
        tau   = self._rng.uniform(self.tau_range[0], self.tau_range[1])
        ratio = self._rng.uniform(self.ratio_range[0], self.ratio_range[1])
        theta = tau * ratio

        plant = FOIPDTPlant(Kv=float(Kv), tau=float(tau), theta=float(theta))
        obs = plant.get_observation_vector()
        return plant, obs